export const environment = {
  appwriteEndpoint: '',
  appwriteProjectId: '',
  appwriteDatabaseId: '',
  appwriteUsersColId: '',
  appwriteTransactionsColId: '',
  apperiteBanksColId: '',
  plaidClientId: '',
  plaidSecret: '',
  plaidEnvironment: '',
  plaidProducts: '',
  plaidEndpoint: '',
  plaidCountryCodes: '',
  plaidBackendUrl: '',
  dwollaEnv: '',
  dwollaKey: '',
  dwollaSecret: '',
  production: false,
};
