export const environment = {
  appwriteEndpoint: process.env['APPWRITE_ENDPOINT'] || '',
  appwriteProjectId: process.env['APPWRITE_PROJECT_ID'] || '',
  appwriteDatabaseId: process.env['APPWRITE_DATABASE_ID'] || '',
  appwriteUsersColId: process.env['APPWRITE_USERS_COL_ID'] || '',
  appwriteTransactionsColId: process.env['APPWRITE_TRANSACTIONS_COL_ID'] || '',
  apperiteBanksColId: process.env['APPWRITE_BANKS_COL_ID'] || '',
  plaidClientId: process.env['PLAID_CLIENT_ID'] || '',
  plaidSecret: process.env['PLAID_SECRET'] || '',
  plaidEnvironment: process.env['PLAID_ENVIRONMENT'] || '',
  plaidProducts: process.env['PLAID_PRODUCTS'] || '',
  plaidEndpoint: process.env['PLAID_ENDPOINT'] || '',
  plaidCountryCodes: process.env['PLAID_COUNTRY_CODES'] || '',
  plaidBackendUrl: process.env['PLAID_BACKEND_URL'] || '',
  dwollaEnv: process.env['DWOLLA_ENV'] || '',
  dwollaKey: process.env['DWOLLA_KEY'] || '',
  dwollaSecret: process.env['DWOLLA_SECRET'] || '',
  production: false,
};
